### ISSUE TITLE
Examples work but response from Google still 403s

### ISSUE THREAD

**Issue by s1rc** [coreruleset/google-oauth2-plugin#1]
I tried your examples in the README.md
```
curl "http://localhost/?state=test&code=test&scope=email+profile+https://www.googleapis.com/auth/userinfo.profile+https://www.googleapis.com/auth/userinfo.email"
curl "http://localhost/?state=test&code=test&scope=email+profile+https://www.googleapis.com/auth/userinfo.profile+https://www.googleapis.com/auth/userinfo.email&inject=data"
```
After the rules are applied, the first succeeds and the second fails with`403`. However the OAuth response from Google is still resulting in `403`.

Here is a OAuth code removed version of what is returned and still failing:
```
http://localhost/auth/google?code=test&scope=email+profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile+openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.metadata.readonly+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.file+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.readonly&authuser=0&prompt=none
```

**Comment by azurit** [comment]
Thanks for reporting this! Can you show me the logs?

**Comment by s1rc** [comment]
Sure!
```
1644270535.352836 [00] [client 127.0.0.1] ModSecurity: Access denied with code 403 (phase 2). Matched phrase ".profile" at ARGS:scope. [file "/etc/modsecurity/owasp-modsecurity-crs/rules/REQUEST-930-APPLICATION-ATTACK-LFI.conf"] [line "97"] [id "930120"] [msg "OS File Access Attempt"] [data "Matched Data: .profile found within ARGS:scope: email profile https:/www.googleapis.com/auth/drive.readonly https:/www.googleapis.com/auth/drive.file https:/www.googleapis.com/auth/drive.metadata.readonly https:/www.googleapis.com/auth/userinfo.profile https:/www.googleapis.com/auth/userinfo.email openid"] [severity "CRITICAL"] [ver "OWASP_CRS/3.3.0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-lfi"] [tag "paranoia-level/1"] [tag "OWASP_CRS"] [tag "capec/1000/255/153/126"] [tag "PCI/6.5.4"] [hostname "modsecurity-spoa-6cdc7484f5-n9hsz"] [uri "http://localhost/auth/google"] [unique_id ""]
```

**Comment by azurit** [comment]
Can you try it with current version? Thank you!

**Comment by s1rc** [comment]
Tried and still getting the same log message/403.
```
1644328913.534385 [00] [client 127.0.0.1] ModSecurity: Access denied with code 403 (phase 2). Matched phrase ".profile" at ARGS:scope. [file "/etc/modsecurity/owasp-modsecurity-crs/rules/REQUEST-930-APPLICATION-ATTACK-LFI.conf"] [line "97"] [id "930120"] [msg "OS File Access Attempt"] [data "Matched Data: .profile found within ARGS:scope: email profile https:/www.googleapis.com/auth/userinfo.profile https:/www.googleapis.com/auth/userinfo.email openid https:/www.googleapis.com/auth/drive.metadata.readonly https:/www.googleapis.com/auth/drive.readonly https:/www.googleapis.com/auth/drive.file"] [severity "CRITICAL"] [ver "OWASP_CRS/3.3.0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-lfi"] [tag "paranoia-level/1"] [tag "OWASP_CRS"] [tag "capec/1000/255/153/126"] [tag "PCI/6.5.4"] [hostname "modsecurity-spoa-56cbf7d6b6-cdj7x"] [uri "http://localhost/auth/google"] [unique_id ""]
```

**Comment by azurit** [comment]
Sorry, found another issue! It should work now.

**Comment by s1rc** [comment]
Looks like it's working! Thank you 🙇

**Comment by morphinestyle** [comment]
😢 I can't get this plugin to work after countless attempts... (version 3.3.2)

I can only make it work with this rule I found on GitHub:
`SecRule ARGS:scope "@contains https://www.googleapis.com/auth/userinfo.profile" "id:'9000000',phase:2,t:none,t:lowercase,pass,nolog,ctl:ruleRemoveById=930120"`

Is it safe?

**Comment by azurit** [comment]
@morphinestyle Can you share logs where requests are blocked?

**Comment by morphinestyle** [comment]
Certainly, this is the auditmodsec.log:

```
ModSecurity: Warning. Matched "Operator `PmFromFile' with parameter `lfi-os-files.data' against variable `ARGS:scope' (Value: `email profile https://www.googleapis.com/auth/userinfo.profile openid https://www.googleapis.com/aut (16 characters omitted)' ) [file "/usr/local/lsws/conf/modsec/owasp-modsecurity-crs-3.0-master/rules/REQUEST-930-APPLICATION-ATTACK-LFI.conf"] [line "78"] [id "930120"] [rev ""] [msg "OS File Access Attempt"] [data "Matched Data: .profile found within ARGS:scope: email profile https:/www.googleapis.com/auth/userinfo.profile openid https:/www.googleapis.com/auth/userinfo.email"] [severity "2"] [ver "OWASP_CRS/3.3.2"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-lfi"] [tag "paranoia-level/1"] [tag "OWASP_CRS"] [tag "capec/1000/255/153/126"] [tag "PCI/6.5.4"] [hostname "test.*********.***"] [uri "/joomla/administrator/index.php"] [unique_id "173705025629.999567"] [ref "o53,8v182,116t:utf8toUnicode,t:urlDecodeUni,t:normalizePathWin,t:lowercase"]
ModSecurity: Access denied with code 403 (phase 2). Matched "Operator `Ge' with parameter `5' against variable `TX:ANOMALY_SCORE' (Value: `5' ) [file "/usr/local/lsws/conf/modsec/owasp-modsecurity-crs-3.0-master/rules/REQUEST-949-BLOCKING-EVALUATION.conf"] [line "80"] [id "949110"] [rev ""] [msg "Inbound Anomaly Score Exceeded (Total Score: 5)"] [data ""] [severity "2"] [ver "OWASP_CRS/3.3.2"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-generic"] [hostname "test.*********.***"] [uri "/joomla/administrator/index.php"] [unique_id "173705025629.999567"] [ref ""]
```

I'm using OpenLitespeed.

And this is my owasp-master.conf, I tried placing the plugin lines before and after `crs-setup.conf`, `REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf`, and `REQUEST-901-INITIALIZATION.conf` with dozens of combinations, but none of them worked:
```
include /usr/local/lsws/conf/modsec/owasp-modsecurity-crs-3.0-master/crs-setup.conf
include /usr/local/lsws/conf/modsec/owasp-modsecurity-crs-3.0-master/rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf
include /usr/local/lsws/conf/modsec/owasp-modsecurity-crs-3.0-master/rules/REQUEST-901-INITIALIZATION.conf

include /usr/local/lsws/conf/modsec/owasp-modsecurity-crs-3.0-master/plugins/google-oauth2-before.conf
include /usr/local/lsws/conf/modsec/owasp-modsecurity-crs-3.0-master/plugins/google-oauth2-config.conf

include /usr/local/lsws/conf/modsec/owasp-modsecurity-crs-3.0-master/rules/REQUEST-905-COMMON-EXCEPTIONS.conf
include /usr/local/lsws/conf/modsec/owasp-modsecurity-crs-3.0-master/rules/REQUEST-910-IP-REPUTATION.conf
include /usr/local/lsws/conf/modsec/owasp-modsecurity-crs-3.0-master/rules/REQUEST-911-METHOD-ENFORCEMENT.conf
include /usr/local/lsws/conf/modsec/owasp-modsecurity-crs-3.0-master/rules/REQUEST-912-DOS-PROTECTION.conf
include /usr/local/lsws/conf/modsec/owasp-modsecurity-crs-3.0-master/rules/REQUEST-913-SCANNER-DETECTION.conf
include /usr/local/lsws/conf/modsec/owasp-modsecurity-crs-3.0-master/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf
include /usr/local/lsws/conf/modsec/owasp-modsecurity-crs-3.0-master/rules/REQUEST-921-PROTOCOL-ATTACK.conf
include /usr/local/lsws/conf/modsec/owasp-modsecurity-crs-3.0-master/rules/REQUEST-930-APPLICATION-ATTACK-LFI.conf
include /usr/local/lsws/conf/modsec/owasp-modsecurity-crs-3.0-master/rules/REQUEST-931-APPLICATION-ATTACK-RFI.conf
include /usr/local/lsws/conf/modsec/owasp-modsecurity-crs-3.0-master/rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
include /usr/local/lsws/conf/modsec/owasp-modsecurity-crs-3.0-master/rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf
include /usr/local/lsws/conf/modsec/owasp-modsecurity-crs-3.0-master/rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf
include /usr/local/lsws/conf/modsec/owasp-modsecurity-crs-3.0-master/rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
include /usr/local/lsws/conf/modsec/owasp-modsecurity-crs-3.0-master/rules/REQUEST-943-APPLICATION-ATTACK-SESSION-FIXATION.conf
include /usr/local/lsws/conf/modsec/owasp-modsecurity-crs-3.0-master/rules/REQUEST-949-BLOCKING-EVALUATION.conf
include /usr/local/lsws/conf/modsec/owasp-modsecurity-crs-3.0-master/rules/RESPONSE-950-DATA-LEAKAGES.conf
include /usr/local/lsws/conf/modsec/owasp-modsecurity-crs-3.0-master/rules/RESPONSE-951-DATA-LEAKAGES-SQL.conf
include /usr/local/lsws/conf/modsec/owasp-modsecurity-crs-3.0-master/rules/RESPONSE-952-DATA-LEAKAGES-JAVA.conf
include /usr/local/lsws/conf/modsec/owasp-modsecurity-crs-3.0-master/rules/RESPONSE-953-DATA-LEAKAGES-PHP.conf
include /usr/local/lsws/conf/modsec/owasp-modsecurity-crs-3.0-master/rules/RESPONSE-954-DATA-LEAKAGES-IIS.conf
include /usr/local/lsws/conf/modsec/owasp-modsecurity-crs-3.0-master/rules/RESPONSE-959-BLOCKING-EVALUATION.conf
include /usr/local/lsws/conf/modsec/owasp-modsecurity-crs-3.0-master/rules/RESPONSE-980-CORRELATION.conf
include /usr/local/lsws/conf/modsec/owasp-modsecurity-crs-3.0-master/rules/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf
```

**Comment by azurit** [comment]
@morphinestyle Please provide full audit log from modsecurity so it contains all relevant information. Thank you.

**Comment by morphinestyle** [comment]
This is the full `auditmodsec.log` file after completely clearing it and then attempting to log in via OAuth (and receiving a 403 error).

```
---iG2UydVX---A--
[16/Jan/2025:20:49:02 +0100] 173705694220.221381 79.13.***.*** 56049 test.*****.*** 443
---iG2UydVX---F--
HTTP/1.1 403
content-type: text/html
cache-control: private, no-cache, max-age=0
pragma: no-cache

---iG2UydVX---H--
ModSecurity: Warning. Matched "Operator `PmFromFile' with parameter `lfi-os-files.data' against variable `ARGS:scope' (Value: `email profile https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/useri (16 characters omitted)' ) [file "/usr/local/lsws/conf/modsec/owasp-modsecurity-crs-3.0-master/rules/REQUEST-930-APPLICATION-ATTACK-LFI.conf"] [line "78"] [id "930120"] [rev ""] [msg "OS File Access Attempt"] [data "Matched Data: .profile found within ARGS:scope: email profile https:/www.googleapis.com/auth/userinfo.profile https:/www.googleapis.com/auth/userinfo.email openid"] [severity "2"] [ver "OWASP_CRS/3.3.2"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-lfi"] [tag "paranoia-level/1"] [tag "OWASP_CRS"] [tag "capec/1000/255/153/126"] [tag "PCI/6.5.4"] [hostname "test.*****.***"] [uri "/joomla/administrator/index.php"] [unique_id "173705694220.221381"] [ref "o53,8v182,116t:utf8toUnicode,t:urlDecodeUni,t:normalizePathWin,t:lowercase"]
ModSecurity: Access denied with code 403 (phase 2). Matched "Operator `Ge' with parameter `5' against variable `TX:ANOMALY_SCORE' (Value: `5' ) [file "/usr/local/lsws/conf/modsec/owasp-modsecurity-crs-3.0-master/rules/REQUEST-949-BLOCKING-EVALUATION.conf"] [line "80"] [id "949110"] [rev ""] [msg "Inbound Anomaly Score Exceeded (Total Score: 5)"] [data ""] [severity "2"] [ver "OWASP_CRS/3.3.2"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-generic"] [hostname "test.*****.***"] [uri "/joomla/administrator/index.php"] [unique_id
"173705694220.221381"] [ref ""]

---iG2UydVX---Z--

```

**Comment by azurit** [comment]
@morphinestyle Please set this in `modsecurity.conf`, reload web server and send new logs:

`SecAuditLogParts ABDEFHIJZ`

Thanks.

**Comment by morphinestyle** [comment]
Here is it @azurit :

```
---9VSh5fDh---A--
[17/Jan/2025:11:00:36 +0100] 173710803697.388730 79.13.***.*** 49700 test.***.*** 443
---9VSh5fDh---B--
GET /joomla/administrator/index.php?option=com_ajax&group=sociallogin&plugin=google&format=raw&code=4%2F0AanRRrtcPgKwhrSUsWmwHFMSDGaB0_8luPZsw_hbrV-dkY7DuAQ7uScdMwqoyWXFPH2cAQ&scope=email+profile+openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email&authuser=0&prompt=none HTTP/1.1
upgrade-insecure-requests: 1
x-browser-year: 2025
x-browser-copyright: Copyright 2025 Google LLC. All rights reserved.
referer: https://accounts.google.com/
sec-ch-ua-platform: "Windows"
host: test.***.***
x-browser-channel: stable
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
sec-fetch-site: cross-site
cookie: osColorScheme=dark; tk_or=%22%22; tk_lr=%22%22; c40ae5222fb979128b008e24534545c7=s6l0pd9142vrdqe76aihoohl1b
accept-encoding: gzip, deflate, br, zstd
accept-language: it-IT,it;q=0.9,en-US;q=0.8,en;q=0.7,fr;q=0.6
accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
x-browser-validation: Nbt54E7jcg8lQ4EExJrU2ugNG6o=
sec-fetch-dest: document
sec-fetch-mode: navigate
sec-fetch-user: ?1
sec-ch-ua: "Google Chrome";v="131", "Chromium";v="131", "Not_A Brand";v="24"
sec-ch-ua-mobile: ?0
priority: u=0, i

---9VSh5fDh---D--

---9VSh5fDh---F--
HTTP/1.1 403
content-type: text/html
cache-control: private, no-cache, max-age=0
pragma: no-cache

---9VSh5fDh---H--
ModSecurity: Warning. Matched "Operator `PmFromFile' with parameter `lfi-os-files.data' against variable `ARGS:scope' (Value: `email profile openid https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/aut (16 characters omitted)' ) [file "/usr/local/lsws/conf/modsec/owasp-modsecurity-crs-3.0-master/rules/REQUEST-930-APPLICATION-ATTACK-LFI.conf"] [line "78"] [id "930120"] [rev ""] [msg "OS File Access Attempt"] [data "Matched Data: .profile found within ARGS:scope: email profile openid https:/www.googleapis.com/auth/userinfo.profile https:/www.googleapis.com/auth/userinfo.email"] [severity "2"] [ver "OWASP_CRS/3.3.2"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-lfi"] [tag "paranoia-level/1"] [tag "OWASP_CRS"] [tag "capec/1000/255/153/126"] [tag "PCI/6.5.4"] [hostname "test.***.***"] [uri "/joomla/administrator/index.php"] [unique_id "173710803697.388730"] [ref "o60,8v182,116t:utf8toUnicode,t:urlDecodeUni,t:normalizePathWin,t:lowercase"]
ModSecurity: Access denied with code 403 (phase 2). Matched "Operator `Ge' with parameter `5' against variable `TX:ANOMALY_SCORE' (Value: `5' ) [file "/usr/local/lsws/conf/modsec/owasp-modsecurity-crs-3.0-master/rules/REQUEST-949-BLOCKING-EVALUATION.conf"] [line "80"] [id "949110"] [rev ""] [msg "Inbound Anomaly Score Exceeded (Total Score: 5)"] [data ""] [severity "2"] [ver "OWASP_CRS/3.3.2"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-generic"] [hostname "test.***.***"] [uri "/joomla/administrator/index.php"] [unique_id "173710803697.388730"] [ref ""]

---9VSh5fDh---I--

---9VSh5fDh---J--

---9VSh5fDh---Z--
```

**Comment by azurit** [comment]
Here is the problem:

`GET /joomla/administrator/index.php?option=com_ajax&group=sociallogin&plugin=google&format=raw&code=4%2F0AanRRrtcPgKwhrSUsWmwHFMSDGaB0_8luPZsw_hbrV-dkY7DuAQ7uScdMwqoyWXFPH2cAQ&scope=email+profile+openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email&authuser=0&prompt=none`

Correct Google OAuth2 callback should contain only these GET parameters:
- state
- code
- scope
- authuser
- hd
- prompt

Your request is sending, additionaly, also these parameters, which is invalid and that's why it is not whitelisted:
- option
- group
- plugin
- format

**Comment by morphinestyle** [comment]
Sure, it’s the statement of the request that Joomla forwards to invoke the plugin (or any component), and it includes these parameters.
I added the arguments, and now it works. Should I keep my modified copy, or do you think it could be included in the official version?

Thank you so much, of course!

**Comment by azurit** [comment]
Are you author of that code?

**Comment by morphinestyle** [comment]
No, the author is Aleeba Ltd, Nicholas Dionysopoulos https://github.com/akeeba/sociallogin

**Comment by azurit** [comment]
This is incorrect usage of Google OAuth2 and won't be part of the official code, sorry.

**Comment by morphinestyle** [comment]
These arguments: option, group, plugin and format are part of the standard URL requests and are in the native Joomla Core code, I'm not a programmer, but at this point wouldn't it make more sense to create a ruleset for Joomla?

**Comment by morphinestyle** [comment]
I think there is also at least MODULE and COMPONENT in the Joomla statement. Nicholas is an expert Joomla programmer, it might be useful to contact him.

**Comment by azurit** [comment]
@morphinestyle If you know his github nickname, please invite him into this discussion. Thanks.

**Comment by morphinestyle** [comment]
Certainly, @nikosdion

**Comment by nikosdion** [comment]
Fabio, you know where to find me if you want a realistic solution to your problem. Sending a return URI with query parameters is neither forbidden nor wrong and Google will correctly reflect them calling back your site. Making an exception is easier than writing your own CMS like this person ultimately wants you to do.

**Comment by morphinestyle** [comment]
Ok, clear.
I’ll keep the modified rule on the server, keeping in mind that this plugin is unusable with Joomla in its original form.
Thank you both so much!

**Comment by nikosdion** [comment]
Thousands of users over several years including my own PRODUCTION blog site say that my plugin works, thank you very much.
Have I ever published software that doesn’t work without modification, or refused to fix a bug in the 22 years I’ve been around Mambo and Joomla? Of course not! So why are you now pretty much accusing me of shipping a broken plugin? Where is that coming from?

**Comment by morphinestyle** [comment]
😁 Nicholas, we didn’t understand each other correctly: I meant that this OWASP rules plugin/patch for Google OAuth is unfortunately unusable in its original form when combined with Joomla. I wasn’t referring to Akeeba Social Login.

LOL🤣

**Comment by nikosdion** [comment]
That makes a lot more sense hahaha!

As for the OWASP core ruleset, it’s really never meant to be used without customization. It’s a security solution. It needs tailoring to your site. As I told you, I use it – but I do customize it to fit each and every site. 

For your info, there’s at least one rule which conflicts with core Joomla. Trying to edit the contact with ID 1 will result in 403. No biggie. Find the rule number in the error log and disable it. It’s SOP for customizing security on your site.

**Comment by morphinestyle** [comment]
Thank you both so much again! @azurit @nikosdion

**Comment by azurit** [comment]
@nikosdion Thanks for joining in! Can you be so kind and point me to the official Google OAuth2 documentation which is reffering to sending custom GET parameters? Thank you.

**Comment by nikosdion** [comment]
@azurit Apologies for the cheap dig earlier. It was a horribly phrased retort I made without thinking at the end of a stressful day.

Regarding your question, the [official Google OAuth2 documentation](https://developers.google.com/identity/protocols/oauth2/web-server) neither explicitly allows, nor explicitly prohibits, redirection URIs with query parameters. The only guidance you get is that sending the Redirect URI as a parameter to the initial request you make to the OAuth2 point is deprecated, i.e. the only valid way to provide a Redirect URI is through the Google Cloud Console interface.

The Google Cloud Console interface does allow redirect URIs with request parameters. These request parameters are included in the redirection made back to the server, therefore proving categorically that they are allowed.

If you were right in your assessment of how the Google OAuth2 API works were correct, the Google Cloud Console would not accept such a redirection URI, and/or the request parameters would not be reflected back to us upon post-login redirection.

This is not an arbitrary interpretation. Over the past 15 years I've written nearly three dozen of those integrations. Most OAuth2 APIs and, generally speaking, APIs with support for server callbacks (which includes payment APIs, for example) do allow request URL parameters. Some of them do not, and it's very clear when this is the case.

For instance, the Microsoft Graph OAuth2 API –which we do presently also integrate with in Akeeba SocialLogin for Joomla– does not allow URL parameters in the redirection URI. If you try to use a URI with query parameters, these parameters are not reflected back upon redirection. Other APIs actively refuse to be configured with such a URI in their interface.

Yes, a workaround is possible. In the case of Microsoft's API we are using the redirection URI `index.php/aksociallogin_finishLogin/microsoft.raw` which has the following problems:
- It is possible that a server-side configuration (e.g. a .htaccess entry) may redirect, or prevent access to that URI.
- It is possible that the client has enabled an SEO extension on their site which will try to redirect this URI to somewhere else, typically `/aksociallogin_finishLogin/microsoft.raw`, which will break the integration.
- If there is a top-level menu item in Joomla! with the slug (alias) `aksociallogin_finishLogin` it will conflict with the integration.

So, while it is technically possible to use a redirection URI without URL parameters, it is fraught with problems. This is a major pain point because Joomla! extensions are _mass distributed_ software, installed and configured by the client. We do not tailor the software for the client's server, we have no say to the server's configuration (or even specifications!), and the clients are typically not very technical which makes explaining and working around issues like that especially problematic. 

As a result, it is a far better policy to use what Joomla! calls the “non-SEF” URL which consists of `index.php` and the URL request parameters you are took umbrage with. After all, this is the canonical way of constructing Joomla! URLs.

In any case, this is all irrelevant. As I told @morphinestyle he just needs to tailor the protection to his site; he's more than capable of it. I know for a fact that he _can_ disable this rule on his site as he has other means which protect it against LFI attacks.

I also want to explicitly state that I fully understand why this rule is written the way it is, I do not consider it wrong in any way, and I do not ask for or even want it to change.

The reason I asked him to contact me instead of continuing here is that the problem ultimately does not lie with the core rules, and there was no point spamming you with irrelevant information that someone might come across in the future and misinterpret as generally safe advice.

Thank you for your time and, again, apologies for my thoughtless wording in my previous reply.

Have a wonderful weekend!

**Comment by azurit** [comment]
@morphinestyle Can you try [this](https://github.com/coreruleset/google-oauth2-plugin/pull/8) PR? See config file and set your custom GET parameters. Also, don't forget to load file `google-oauth2-config.conf` before `google-oauth2-before.conf`.

**Comment by azurit** [comment]
@nikosdion Don't worry pal!

This is the first time i see someone using custom query parameters as part of a callback URL - no one from users of this plugin and also any of my customers. I'm pretty sure this even wasn't possible some time ago as you can find lots of questions about using custom parameters with Google OAuth2 on Stackoverflow (for example [here](https://stackoverflow.com/questions/7722062/google-oauth-2-0-redirect-uri-with-several-parameters), [here](https://stackoverflow.com/questions/48914519/how-to-add-a-param-to-google-oauth-2) or [here](https://stackoverflow.com/questions/79034026/how-to-extend-google-login-oauth2-with-custom-user-info-parameters-on-the-scre)).

Anyway, i introduced a workaround for this, see above.

**Comment by nikosdion** [comment]
@azurit Thank you for your understanding, and the context for your reply. I understand how you came to that conclusion. Unfortunately, it's not the first time I've seen outdated and/or nonsensical information in StackOverflow. I have been using this type of return URI (with query parameters) [since 2017](https://github.com/akeeba/sociallogin/blob/94b6bea33562193dd05a357ce5fbe51a6e9c94a2/plugins/sociallogin/google/google.php#L158), thus predating the earliest of the questions you linked by a full year. It's been well over seven and half years and it has worked perfectly fine on thousands of sites across dozens, if not hundreds, of hosts 🤷‍♂

**Comment by morphinestyle** [comment]
@azurit 
**If I add the arguments to this new code, it works correctly.**
I added the arguments (option, group, plugin, format) in the `google-oauth2-config.conf` file as instructed, and it works!
`setvar:'tx.google-oauth2-plugin_whitelisted_parameters=/option/ /group/ /plugin/ /format/'"`

However, be aware: **if I use this new code --as it is here-- without adding the arguments, it doesn’t work, and it also breaks ModSecurity entirely (ModSecurity stops functioning)**.

**Comment by azurit** [comment]
@morphinestyle Do you use nginx or Apache?

**Comment by morphinestyle** [comment]
I use Openlitespeed.
(Here you and Nikolas will eat me)

**Comment by azurit** [comment]
Fixed, merged, thanks.

**Comment by morphinestyle** [comment]
I'll try it tomorrow.
Thanks to you!

**Comment by morphinestyle** [comment]
@azurit Thank you! It Works Well!
